CREATE TABLE orders (
    id INT NOT NULL AUTO_INCREMENT,
    fname VARCHAR(255) NOT NULL,
    lname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    del_address VARCHAR(255) NOT NULL,
    pizza VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

